### ISSUE TITLE
When I run example_free_water.py, kwave_bin_driver.py reports an error that the system can't find the file specified

### ISSUE THREAD

**Issue by 1413194910** [pty0220/FUS_acousitc_simulation#2]
![1716952063425](https://github.com/pty0220/FUS_acousitc_simulation/assets/60837815/ebbe56bd-58fa-46fd-94a8-da480b609a29)

**Comment by pty0220** [comment]
Here, the k-wave core files such as ex. dll should be included. These can be downloaded from the k-wave website. Due to their large size, they are not included in this repository.

If you want to use k-wave with Python, I recommend https://github.com/waltsims/k-wave-python. This allows you to use the latest version of k-wave and supports almost all k-wave functions.

If you need code for applying tFUS, I also recommend https://github.com/sitiny/BRIC_TUS_Simulation_Tools.

Both use the latest version of k-wave, providing more functional benefits.

**Comment by 1413194910** [comment]
I have followed your advice and the problem has been successfully resolved. Thank you very much for your help!
